#ifndef RRC_H_
#define RRC_H_

#include "common/stl.h"

#define DEMOTE_TIMER 10

#define UPLINK_POWER 1.189
#define DOWNLINK_POWER 0.43778

#define CONNECTED_POWER 1.450
#define BASELINE_POWER 0.800

#define ACTIVE_COST_DOWN (CONNECTED_POWER-BASELINE_POWER+DOWNLINK_POWER)
#define ACTIVE_COST_UP (CONNECTED_POWER-BASELINE_POWER+UPLINK_POWER)
#define PASSIVE_COST (CONNECTED_POWER-BASELINE_POWER)

#endif /* RRC_H_ */

